name: Temp Deployment to GCP

on:
  push:
    branches: ["develop"]
    paths:
      - 'common/**'
      - 'chat-service/**'
#      - 'match-service/**'
#      - 'member-service/**'
      - 'notification-service/**'
#      - 'payment-service/**'
      - 'build.gradle'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  REGION: asia-northeast3

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service:
          - chat
#          - match
#          - member
          - notification
#          - payment

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      # 변경 감지
      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - '${{ matrix.service }}-service/**'
              - 'common/**'
              - 'build.gradle'
              - 'settings.gradle'

      # --- 변경된 경우에만 실행 ---
      - name: Set up JDK 17
        if: steps.changes.outputs.src == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        if: steps.changes.outputs.src == 'true'
        run: |
          chmod +x gradlew
          ./gradlew :${{ matrix.service }}-service:bootJar -x test

      - name: Login to Docker Hub
        if: steps.changes.outputs.src == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Docker Hub
        if: steps.changes.outputs.src == 'true'
        run: |
          IMAGE_TAG="${{ env.DOCKER_USERNAME }}/bebee-${{ matrix.service }}:latest"
          
          docker build -t $IMAGE_TAG -f ${{ matrix.service }}-service/Dockerfile .
          docker push $IMAGE_TAG
          
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      
      - name: Google Auth
        if: steps.changes.outputs.src == 'true'
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SA_EMAIL }}'

      - name: Deploy to Cloud Run
        if: steps.changes.outputs.src == 'true'
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: bebee-${{ matrix.service }}
          region: ${{ env.REGION }}
          image: ${{ env.IMAGE_TAG }}
          flags: '--timeout=300s'
          env_vars: |
            SPRING_PROFILES_ACTIVE=dev
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=3306
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            MONGODB_HOST=${{ secrets.MONGODB_HOST }}
            MONGODB_PORT=27017
            REDIS_HOST=${{ secrets.REDIS_HOST }}
            REDIS_PORT=6379
            SPRINGDOC_API_HOST=${{ secrets.SERVER_HOST}}
            SPRINGDOC_API_DESC="임시 GCP 개발 서버"
            
